# Site settings
title: My Blog
description: A blog about Rakesh Kumar
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "127.0.0.1:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rakesh Kumar
user_description: I am a Computer Science and Engineering student at National Institute of Technology, Hamirpur. I am interested in competitive programming, Developing Android Applications. Currently I am looking for Summer and remote internship where I can upgrade my skills and leaning new technologies.
user_title: Student & Software Developer

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
